matrix:
  include:
  - os: linux
    language: python
    python: "2.7"
    install: python setup.py sdist bdist_wheel
  - os: linux
    language: python
    python: "3.7-dev"
    install: python setup.py sdist bdist_wheel
  - os: windows
    language: generic
    install: python2 --version
  - os: windows
    language: generic
    install: python --version

before_install:
  - chmod +x scripts/sfml_install.sh
  # The '.' executes this script within the current Bash shell.
  - . scripts/sfml_install.sh $TRAVIS_OS_NAME
  - pip install -r requirements.txt
    
    
    
notifications:
  email: false

install:
  echo "Attempt at a common install command!"
#   # Handles the push to pypi.
#   - twine upload --repository-url https://upload.pypi.org/legacy/ dist/*

script:
-  ls dist/
#   TODO: Explore integration testing.
#   - pytest cython_example_proj
  
# deploy:
#   provider: pypi
#   user: jawaff
#   password:
#     secure: <SOME_KEY>
#   on:
#     branch: master
