env:
  global:
    - SFML_VERSION=2.3.2

matrix:
  include:
  - os: linux
    language: python
    python: "2.7"
  - os: linux
    language: python
    python: "3.7-dev"
  - os: windows
    # Travis' Windows Env doesn't support a Python language.
    language: shell

before_install:
  - chmod +x scripts/sfml_install.sh
  # The '.' executes this script within the current Bash shell.
  - . scripts/sfml_install.sh $TRAVIS_OS_NAME $SFML_VERSION
  # We can only support up to Python 3.6.6, because our SFML-2.3.2 and Python 3.6.6 are compiled against VS14 (2015).
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export PYTHON_VERSION='3.6.6'; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export PYTHON_HOME='C:\Python36'; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export VS14_BIN='C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin'; fi
  # Sets up the python/pip/vs14 environment that is expected later in this script for Windows.
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell -ExecutionPolicy RemoteSigned -File ./scripts/windows_env_setup.ps1 $PYTHON_VERSION $PYTHON_HOME; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export PATH="$PYTHON_HOME:$PYTHON_HOME\Scripts:$VS14_BIN:$PATH"; fi
    
notifications:
  email: false

install:
  - pip install -r requirements.txt
  - python setup.py build

script:
-  ls build/

before_deploy:
  - ls
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ls __pycache__; fi

deploy:
  provider: pypi
  user: jawaff
  password:
    secure: JEymdZcXAs0wbjL6JxBfrdvXMS4dK+FFwQwgAx2jiMJEhWTie6F10UxHil75YWKxbBaEux84P+6rMSZBV7HDJk6hMhfbDOh+hxC6UKJZyz9oY9/r8muYchex3JiVd/ymUUHM4i0pOb09u5dt3e8RFYoc33fJDnzMIh7yH6Qv6aZoL0TN/ILLhahU9MNJLZXGqnq64n77GoQs3BahYuaT1/3Mk5ReaJeCkdzQkJImYCFA6Glvs3ninvtk+xsMBlFjAbG7ByV2Xk/imZoUdxOVoGI1gRqq2ru/7cerM2ASEn47t4KjEZ7UGkIoGWh0pmqPQRg+gxLLL19R8BAuhLYPSzc/GGnlrneSCXoQWG489G0UjZF9gAQ3QHxxI9PYN20RBFOIob38RvIKo39DpSSCk9pC7hH/K04zliqKFTcC/X3+ubbjHMFdF2zyarmVZTngXUmsi+QpFA4ExWhvjLS1H10Hq9pFelumFPmkBruq2sXyDSd7lWWzplRCCUExo77WdMX+rrWWk/E/Zpkkt4rQoGIvDb8O5qMT2SGSthKYHJLr6lqFOWxkS0eC7iQLWG/11dtoxybCQ9zBJdR17UNLSysT3A4RSvbjYo7iOissbIsOhum9EDs17nm8AIiYjvtwTwNdcTS8hqNA9DUmCcqvZnaV6dJ6tkDb8VVOTk0KBIM=
  distributions: "sdist bdist_wheel"
  on:
    branch: master
    tags: true
