notifications:
  email: false

env:
  global:
    - SFML_VERSION=2.3.2
    
# Caches are only shared by builds with the same OS and environment variables.
# Thus this OS specific dependency directory can safely be cached.
cache:
  directories:
    - extlibs/SFML-$SFML_VERSION

cache:
  timeout: 180
    
matrix:
  include:
    - os: linux
      language: shell
      sudo: required
      services:
        - docker
      env:
        - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
        # Wheels will be generated in the before_deploy phase.
        - DISTRIBUTIONS=''
    - os: windows
      # Travis' Windows Env doesn't support a Python language.
      language: shell
      env:
        # We can only support up to Python 3.6.6, because our SFML-2.3.2 and Python 3.6.6 are compiled against VS14 (2015).
        - PYTHON_VERSION=3.6.6
        - PYTHON_HOME='C:\Python36'
        - VS14_BIN='C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin'
        - PATH="$PYTHON_HOME:$PYTHON_HOME\Scripts:$VS14_BIN:$PATH"
        # Only one sdist can be published to pypi per version.
        - DISTRIBUTIONS='sdist bdist_wheel'

before_install:
  - chmod +x scripts/sfml_install.sh
  - chmod +x scripts/build_linux_wheels.sh

install:
  - ./scripts/sfml_install.sh $TRAVIS_OS_NAME $SFML_VERSION
  - if ! [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      ./scripts/windows_base_install.sh $PYTHON_VERSION $PYTHON_HOME
      pip install -r requirements.txt
      python setup.py build;
    else if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      # Downloads a special CentOS docker image for building manylinux wheels.
      docker pull $DOCKER_IMAGE;
    fi

script:
  - ls extlibs/
  - ls extlibs/SFML-$SFML_VERSION
  # Executes manylinux wheel build on a CentOS docker image.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/scripts/build_linux_wheels.sh $TRAVIS_OS_NAME $SFML_VERSION; fi
  # TODO Execute Windows Tests

before_deploy:
  if ! [[ $TRAVIS_TAG ]]; then
    # Versioneer creates these .pyc files during the install phase.
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm -f versioneer.pyc; fi
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then rm -r __pycache__; fi
    rm -r build/
    # We shall use the less hazardous git stash command so that the SFML binaries are intact for the build.
    git stash;
  fi

deploy:
  provider: pypi
  user: jawaff
  server: https://test.pypi.org/legacy/ # Remove for deployment to official PyPi repo
  # This environment variable can be set as a secret environment variable in the TravisCI project's settings.
  password: $PYPI_PASSWORD
  # Prevents 'git stash -all' command that will remove the downloaded SFML binaries -- the '--all' bypasses the .gitignore.
  skip_cleanup: true
  distributions: $DISTRIBUTIONS
  on:
    repo: jawaff/python-sfml
    # Restricts deployments to version tagged commits -- only valid versions allowed as well.
    tags: true
    all_branches: true
    # Version tags must be of the following pattern and there must be distributions called out in order to deploy.
    condition: $TRAVIS_TAG =~ ^v([0-9]+\.){2,3}[0-9]+(-\.+)?$
