env:
  global:
    - SFML_VERSION=2.3.2

matrix:
  include:
  - os: linux
    language: python
    python: "2.7"
  - os: linux
    language: python
    python: "3.7-dev"
  - os: windows
    # Travis' Windows Env doesn't support a Python language.
    language: shell

before_install:
  - chmod +x scripts/sfml_install.sh
  # The '.' executes this script within the current Bash shell.
  - . scripts/sfml_install.sh $TRAVIS_OS_NAME $SFML_VERSION
  # We can only support up to Python 3.6.6, because our SFML-2.3.2 and Python 3.6.6 are compiled against VS14 (2015).
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export PYTHON_VERSION='3.6.6'; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export PYTHON_HOME='C:\Python36'; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export VS14_BIN='C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin'; fi
  # Sets up the python/pip/vs14 environment that is expected later in this script for Windows.
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell -ExecutionPolicy RemoteSigned -File ./scripts/windows_env_setup.ps1 $PYTHON_VERSION $PYTHON_HOME; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export PATH="$PYTHON_HOME:$PYTHON_HOME\Scripts:$VS14_BIN:$PATH"; fi
    
notifications:
  email: false

install:
  - pip install -r requirements.txt
  - python setup.py build

script:
-  ls build/

deploy:
  provider: pypi
  user: jawaff
  password:
    secure: g9Kw8i/BT37JMOlNZMa7LStu2G8nWqkTkvBQjPMjYsxRwLCMhRMExyRJDLs6bruM56WmLFvl7jsHF4LWxOr2oN0uG+lOQxGy+ug580WJD/hlxKk19D0MreB1UUEuEDPlsdjIu+eTlqYEEqKN0PutoIzpWxXsCrnWYcCzS36Lbwf2UCsYgqYb34GT470ye49aezGPxIj43GGICtXzVdIRTKR9N9vyFrgXrxw1NMjPdacCWFaxH8Nr0BlCaM+Zfb+HgWqIbpk7lD6uZQO/WURdEEyNefooddthiB/h2yocxzhSPheYZJD+IXwpCHEtgo1Z4TXsrU5tT62lmeCEDgvUWWvDr9mJjTIExg5PkvYBjWKv6yUmY7LPrw+JFCzbF1fm1VmcPdMNhh1kJf2GxvvyVOIW5DPF4dhgkU5t3SLS1v3OQAoXAhYCoRAkdM1Dcdud814DRUiM0psTv6ZW0tnr72Rw7QFfXPjnwJv8LjvYpkT/QPdFte/AmvoY3WdrCsUEBcor8Dygi8yNvY5cOqS3RFFQ43SpZroxEwtryKTJm3DLZhtjwzcH8iHM6QhnIQKplPIdyC3r0X7XJghepc2JxtnPSp+8p47xK2CCOf0IAjd47U8cmOzqp74g2Ma6Onvb353KfubO8jo7gFfYtZ1wrqeW4i4nxpE+cjwqaPqiu9U=
  on:
    branch: master
