matrix:
  include:
  # - os: linux
  #   language: python
  #   python: "2.7"
  #   install: python setup.py sdist bdist_wheel
  # - os: linux
  #   language: python
  #   python: "3.7-dev"
  #   install: python setup.py sdist bdist_wheel
  - os: windows
    # Travis' Windows Env doesn't support a Python language.
    language: shell
    # The python version will have to be selected based off the executable that is used.
    install: python setup.py sdist bdist_wheel
  # - os: windows
  #   # Travis' Windows Env doesn't support a Python language.
  #   language: bash
  #   install: 
  #     python --version
  #     pip --version

before_install:
  - chmod +x scripts/sfml_install.sh
  # The '.' executes this script within the current Bash shell.
  - . scripts/sfml_install.sh $TRAVIS_OS_NAME
  - powershell -ExecutionPolicy Bypass -Command ./scripts/windows_env_setup.ps1
    
notifications:
  email: false

install:
  echo "Attempt at a common install command!"
#   # Handles the push to pypi.
#   - twine upload --repository-url https://upload.pypi.org/legacy/ dist/*

script:
-  ls dist/
#   TODO: Explore integration testing.
#   - pytest cython_example_proj
  
# deploy:
#   provider: pypi
#   user: jawaff
#   password:
#     secure: <SOME_KEY>
#   on:
#     branch: master
