env:
  global:
    - SFML_VERSION=2.3.2
    
# Caches are only shared by builds with the same OS and environment variables.
# Thus this OS specific dependency directory can safely be cached.
cache:
  directories:
    - extlibs/SFML-$SFML_VERSION
    
matrix:
  include:
    - os: linux
      language: python
      python: 2.7
      cache: pip
    - os: linux
      language: python
      python: 3.7-dev
      cache: pip
    - os: windows
      # Travis' Windows Env doesn't support a Python language.
      language: shell
      env:
        # We can only support up to Python 3.6.6, because our SFML-2.3.2 and Python 3.6.6 are compiled against VS14 (2015).
        - PYTHON_VERSION=3.6.6
        - PYTHON_HOME='C:\Python36'
        - VS14_BIN='C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin'
      cache:
        directories:
          - 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\'

      
before_install:
  - chmod +x scripts/sfml_install.sh
  - chmod +x scripts/env_setup.sh
  # This works in any OS's bash environment so far.
  - ./scripts/sfml_install.sh $TRAVIS_OS_NAME $SFML_VERSION
  # Sets up the python/pip/vs14 environment that is expected later in this script for Windows.
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell -ExecutionPolicy RemoteSigned -File ./scripts/windows_base_install.ps1 $PYTHON_VERSION $PYTHON_HOME; fi
  # The '.' executes this script within the current Bash shell -- allows environment variable updates.
  - . scripts/env_setup.sh $TRAVIS_OS_NAME $SFML_VERSION
  # This has to be set within the .travis scipt in order to persist into the install phase.
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export PATH="$PYTHON_HOME:$PYTHON_HOME\Scripts:$VS14_BIN:$PATH"; fi
    
notifications:
  email: false

install:
  - pip install -r requirements.txt
  - python setup.py build

script:
-  ls build/

before_deploy:
  # Versioneer creates these .pyc files during the build/test phase.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm -f versioneer.pyc; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then rm -r __pycache__; fi
  # The '.' executes this script within the current Bash shell -- allows environment variable updates.
  - . scripts/env_setup.sh $TRAVIS_OS_NAME $SFML_VERSION
  # This has to be set within the .travis scipt in order to persist into the deploy phase.
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export PATH="$PYTHON_HOME:$PYTHON_HOME\Scripts:$VS14_BIN:$PATH"; fi

deploy:
  provider: pypi
  user: jawaff
  server: https://test.pypi.org/legacy/ # Remove for deployment to official PyPi repo
  password:
    secure: uKgDHmH3lWednGmjayYTbTs9kcANeFUdNyXRniZJdhEr0yIp7izcTXy7huxisKpNHzv8mlwsWMpKKtCB4Hck44g63lCHgmETlIMGMM8CHT2syP2efo59DvdeXUXgCWL9FegdZ98g6HF6VK+cnEVMSLC14hDEYfiOFINUf3fpljwN0xD8nLLRKCpGD8rgjurCWG0U9OytnKkerwlDqR4/4RIpeNhMcttVaGTlinQFSME44wXeUDDVPyi7gt3w2vrveBDHv1buxLOjrMuEwsnj1cgJyvJ+b5F7i9FifIK1BxOCY2q9nS9O50sFh+oAZVz+Ranz/cHOuR9Wfpp0BHdw4sFAOLXFg9dyBC4Ks0HSpHBMmduZVc7US/RxEfYnTPDfPb1nNYW6gY7k6yJ9Hg0PK9GxMVeEYEGR6a2yplonAAfs2P2gogpcxbjCUMEaubhRo4+ylySBvCmFPYuwAL5np8fbHvGBQyxaxIlV8YjRhnfbn8a406toc2kWmHtrI4tvieaAYS/v7hVfcgkIwsipPefcp4qQLfvont26SLAzqraTJaf7baiAOj3hmSQ+QMkAoVoL05Ss2OFi47iL27wDPO+4xXNklprkERkImmr5z4/FheOLI9i0ZKWdK7XAue63IPeUBKXB6NY3E2WRHTXYynbCmEb1AIDnAHDK3W4AW8Y=
  distributions: sdist bdist_wheel
  on:
    repo: jawaff/python-sfml
    branch: master
    tags: true
